services:
  blog:
    image: el-choco/blog:latest
    restart: unless-stopped
    environment:
        TZ: Europe/Berlin
        BLOG_TITLE: Blog
        BLOG_NAME: Max Musermann
        BLOG_NICK: username
        BLOG_PASS: password
        BLOG_LANG: en
    ports:
      - 8011:80
    volumes:
      - ./data:/var/www/html/data

